matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode8.3 # see osx+jdk versions at https://docs.travis-ci.com/user/reference/osx#OS-X-Version
  allow_failures:
    - os: linux
      jdk: openjdk10
    - os: osx

language: java

sudo: false # faster builds

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: "./mvnw clean test -Pcoverage -B"

cache:
  directories:
    - '$HOME/.m2/repository'
