language: java

sudo: false # faster builds

jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: "./mvnw clean test -Pcoverage -B"

cache:
  directories:
    - '$HOME/.m2/repository'
