matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk10
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode8.3 # see osx+jdk versions at https://docs.travis-ci.com/user/reference/osx#OS-X-Version
  allow_failures:
    # who use osx?
    - os: osx
    # non-LTS jdk can fail, I won't use it in production but it's useful to prepare migration to next LTS jdk
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk10

language: java

sudo: false # faster builds

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: "./mvnw clean test -Pcoverage -B"

cache:
  directories:
    - '$HOME/.m2/repository'
