matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
  allow_failures:
    # snapshot and non-LTS jdk can fail, I won't use it in production but it's useful to prepare migration to next LTS release
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11

language: java

sudo: false # faster builds

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: "./mvnw clean test -Pcoverage -B"

cache:
  directories:
    - '$HOME/.m2/repository'

git:
  depth: 3
