services:
  - docker

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
  #allow_failures:
    # snapshot and non-LTS jdk can fail, I won't use it in production but it's useful to prepare migration to next LTS release
    #- os: linux
    #  jdk: openjdk12

language: java

before_install:
  - chmod +x mvnw
  - mkdir ~/manon-maria-db
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo netstat -antp
  - docker-compose --version
  - docker-compose -f ./docker/docker-compose.yml up -d maria

script: "./mvnw clean verify -P test-real,coverage,ci -B"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2'

git:
  depth: 3
