services:
  - docker

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: linux
      jdk: openjdk13
  allow_failures: # snapshot and non-LTS jdk can fail, I won't use it in production but it's useful to prepare migration to next LTS release
    - jdk: openjdk12
    - jdk: openjdk13

language: java

before_install:
  - chmod +x mvnw
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo netstat -antp
  - docker-compose --version
  - export MANON_TEST_SQL_JDBC_URL="jdbc:mariadb://127.0.0.1:3307/manon?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true"
  - export MANON_TEST_BATCH_SQL_JDBC_URL="jdbc:mariadb://127.0.0.1:3308/manon_batch?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true"
  - export MANON_TEST_REDIS_PORT=6380
  - docker-compose -f ./docker/docker-compose-test.yml up -d
  - sudo netstat -antp

script: "./mvnw clean verify -P test-real,coverage,ci -B"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2'

git:
  depth: 3
