version: build-{build}.{branch}
clone_depth: 10

branches:
  only:
    - spring5

platform: x64

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk9
  - SET PATH=C:\Program Files\Java\jdk9\bin;%PATH%

build_script:
  - gradlew clean build -x test

test_script:
  - gradlew clean test jacocoTestReport -Pcoverage=true

cache:
- C:\Users\appveyor\.gradle
