version: build-{build}.{branch}
clone_depth: 3

platform: x64

install:
  # JDK installation via: https://chocolatey.org/packages/jdk11
  - cinst jdk11 -params 'installdir=C:\\jdk11'
  - SET JAVA_HOME="C:\jdk11"
  - SET PATH=%JAVA_HOME%\bin;%PATH%

build_script:
  - mvnw clean package -DskipTests

test_script:
  - mvnw test -Pembed-win,ci -B

cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.embedmongo
