version: build-{build}.{branch}

branches:
  only:
    - spring5

platform: x64

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk9
  - SET PATH=C:\Program Files\Java\jdk9\bin;%PATH%

build_script:
  - mvnw clean package

test_script:
  - mvnw clean test
