version: build-{build}.{branch}
clone_depth: 10

branches:
  only:
    - spring5

platform: x64

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk9
  - SET PATH=C:\Program Files\Java\jdk9\bin;%PATH%

build_script:
  - mvnw clean package -DskipTests

test_script:
  - mvnw test

cache:
- C:\Users\appveyor\.m2
