### DEV CONFIGURATION for local application with existing MariaDB ###  (warning: avoid tabs, indent with two spaces)

spring:
  datasource:
    username: ${MANON_SQL_USERNAME:root}
    password: ${MANON_SQL_PASSWORD:woot}
    url: ${MANON_SQL_JDBC_URL:jdbc:mariadb://localhost:3306/manon_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true}
