   ### PRODUCTION CONFIGURATION for production application ###  (warning: avoid tabs, indent with two spaces)
  
spring:
  data:
    mongodb:
      database: manonprod
      username: MONGODB_USERNAME_HERE
      password: MONGODB_PASSWORD_HERE
      authentication-database: manonprod
  jpa.hibernate.ddl-auto: update

manon:
  admin:
    defaultAdmin:
      username: MANON_ADMIN_USERNAME_HERE
      password: MANON_ADMIN_PASSWORD_HERE
