### PRODUCTION CONFIGURATION for production application ###  (warning: avoid tabs, indent with two spaces)

spring:
  data:
    mongodb:
      host: ${MANON_PROD_MONGODB_HOST}
      port: ${MANON_PROD_MONGODB_PORT}
      database: ${MANON_PROD_MONGODB_DB_NAME}
      username: ${MANON_PROD_MONGODB_USERNAME}
      password: ${MANON_PROD_MONGODB_PASSWORD}
      authentication-database: ${MANON_PROD_MONGODB_AUTH_DB_NAME}
  datasource:
    username: ${MANON_PROD_SQL_USERNAME}
    password: ${MANON_PROD_SQL_PASSWORD}
    url: ${MANON_PROD_SQL_JDBC_URL}
  jpa.hibernate.ddl-auto: update

manon:
  admin:
    default-admin:
      username: ${MANON_PROD_ADMIN_USERNAME}
      password: ${MANON_PROD_ADMIN_PASSWORD}
