### PRODUCTION CONFIGURATION for production application ###  (warning: avoid tabs, indent with two spaces)

spring:
  datasource:
    username: ${MANON_PROD_SQL_USERNAME}
    password: ${MANON_PROD_SQL_PASSWORD}
    url: ${MANON_PROD_SQL_JDBC_URL}
  jpa.hibernate.ddl-auto: update

manon:
  admin:
    default-admin:
      username: ${MANON_PROD_ADMIN_USERNAME}
      password: ${MANON_PROD_ADMIN_PASSWORD}
