   ### DEV CONFIGURATION for local application ###  (warning: avoid tabs, indent with two spaces)

spring:
  data:
    mongodb:
      database: manondev
      username: root
      password: woot
      authentication-database: manondev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: woot
    url: jdbc:mysql://127.0.0.1:3307/manon_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true
  jpa.hibernate.ddl-auto: create-drop
