### DEV CONFIGURATION for local application ###  (warning: avoid tabs, indent with two spaces)

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: manondev
      username: root
      password: woot
      authentication-database: manondev
