version: '3'

services:

  # ----------------------------------------
  # --- Application
  # ----------------------------------------

  manon:
    container_name: manon
    image: lermitage-manon:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - ~/manon-app-logs:/logs
    depends_on:
      - maria

  maria:
    container_name: maria
    image: mariadb:10.3.12-bionic # see https://hub.docker.com/_/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - ~/manon-maria-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon

  # ----------------------------------------
  # --- Frontend proxy
  # ----------------------------------------

  nginx:
    container_name: nginx
    image: nginx:1.15.8 # see https://hub.docker.com/_/nginx/
    ports:
      - "8000:80"
    volumes:
      - ~/manon-nginx-logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - manon # to proxy app
