version: '3.4'

services:

  maria:
    container_name: maria-test
    image: mariadb:10.3.15 # see https://hub.docker.com/_/mariadb/
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon
