version: '3.4'

services:

  # ----------------------------------------
  # --- Application
  # ----------------------------------------

  manon:
    container_name: manon
    image: lermitage-manon:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - ~/manon-app-logs:/logs
    environment:
      MANON_SQL_USERNAME: root
      MANON_SQL_PASSWORD: woot
      MANON_SQL_JDBC_URL: jdbc:mariadb://maria:3306/manon?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true
    depends_on:
      - maria
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  maria:
    container_name: maria
    image: mariadb:10.3.15 # see https://hub.docker.com/_/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - ~/manon-maria-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/3306' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ----------------------------------------
  # --- Frontend proxy
  # ----------------------------------------

  nginx:
    container_name: nginx
    image: nginx:1.15.12-alpine # see https://hub.docker.com/_/nginx/
    ports:
      - "8000:80"
    volumes:
      - ~/manon-nginx-logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - manon # to proxy app
